package.json

These are not required at runtime, typechecking stuff should be in devDependencies

Move typescript types to dev dependencies

---

src/ExpoClient.ts

According to the [documentation](https://docs.expo.io/versions/latest/guides/push-notifications/#response-format), a **Push Ticket** has both an id and status field:
> Upon success, the HTTP response will be a JSON object whose data field is an array of push tickets, each of which corresponds to the message at its respective index in the request. Continuing the above example, this is what a successful response body looks like:
> 
> ```
> {
>   "data": [
>     {"status": "ok", "id": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"},
>     {"status": "ok", "id": "YYYYYYYY-YYYY-YYYY-YYYY-YYYYYYYYYYYY}
>   ]
> }
> ```
However, right now `ExpoPushTicket` only has an `id` field, so typescript throws an error (`Property 'status' does not exist on type 'ExpoPushTicket'.`) if you try to check the status. …

Update push ticket type to match documentation

---

src/ExpoClient.ts

I think this is a better fit for what the function actually does: we don't know the type of the thing coming in, but we do know the type if it returns true.
https://www.typescriptlang.org/docs/handbook/advanced-types.html#using-type-predicates
note: I did this in GitHub's web interface so I didn't test if it compiles, although it *should* (famous last words)

Update isExpoPushToken type signature

---

README.md
package.json
src/ExpoClient.ts
src/__tests__/ExpoClient-test.ts

Added an option to the constructor, updated the readme and added tests for with and without the option supplied.

Add support for access tokens

---

package.json
src/ExpoClient.ts
src/ExpoClientValues.ts
src/__tests__/ExpoClient-test.ts
tsconfig.json
yarn.lock

We'll be adding rate limiting to the push/send API soon, so before that it'd be good to have this library handle 429s gracefully.
Add `promise-retry` with 2 retries and exponential backoff.
Run unit test.

feat: add exponential backoff and retries for push/send

---

README.md
src/ExpoClient.ts
src/__tests__/ExpoClient-test.ts

Based on this FCM related blogpost here, [https://expo.dev/blog/expo-adds-support-for-fcm-http-v1-api](url) it seems like there's no solution for people like us who use the Node SDK to send push notifications.
This change adds support for initiating `ExpoClient` with another optional parameter called `useFCM: true` which appends the necessary query string to the `/push/send` (?useFcmV1=true)

Added support for FCM V1 configuration

---

.github/workflows/tests.yml
package.json
src/ExpoClient.ts
src/__tests__/ExpoClient-test.ts
yarn.lock

This updates various devDependencies like Jest and Prettier and also the GHA Actions packages.

Upgrade devDependencies and CI Actions

---

src/__tests__/ExpoClient-test.ts

I replaced toThrowError with toThrow because toThrowError is deprecated.

Replace `toThrowError` with `toThrow`

---

src/ExpoClient.ts

When an error is generated by Expo attempting to send a push notification, it includes the `expoPushToken` in the result depending on the type of error. It is included for type `DeviceNotRegistered` where it is important to know what token failed so it can be removed from the user, especially if a given user has multiple tokens associated.

Add expoPushToken to ExpoPushErrorReceipt type

---

src/ExpoClient.ts
src/ExpoClientValues.ts
src/__tests__/ExpoClient-test.ts

- Move constants into ExpoClientValues
- Allow use for Expo internal push hydrant testing with env variable EXPO_BASE_URL
- Fix and refactor unit tests

chore: Refactor constants

---

README.md
src/ExpoClient.ts
src/__tests__/ExpoClient-test.ts

`useFcmV1` defaults to true to align with push service change:
- Will not be added to the URL unless it is set to `false`
- Update `README.md` with comments on the change
- Update unit test

fix: useFcmV1 should default to true and be deprecated

---

src/ExpoClientValues.ts
src/__tests__/ExpoClient-test.ts

It's easy for this mock to fall out of sync with the actual module, and solutions which would prevent this would be verbose and cluttered.  The only thing it achieves is keeping the tests fast with a lower retry timeout, and that can also be achieved with a switch on `NODE_ENV`.

Remove values mock from test

---

package.json
src/ExpoClient.ts
src/ExpoClientValues.ts
src/__tests__/ExpoClient-test.ts
tsconfig.build.json
tsconfig.json

I noticed that with the codecov action broken, coverage had dropped without us noticing (#88), but not very far.  It was easy to bring it back and add a threshold to keep it there.

100% test coverage

---

src/__mocks__/node-fetch.ts
src/__tests__/ExpoClient-test.ts

Using jest to mock at the boundaries of node-fetch directly is simpler, and makes type mismatches between the mock and the real module less likely.

Remove fetch-mock

---

src/ExpoClient.ts

This is for iOS only. Android sounds are specified via `channelId` [docs](https://docs.expo.dev/versions/latest/sdk/notifications/#handling-notification-channels).
When you configure a sound in our config plugin ([docs.expo.dev/versions/latest/sdk/notifications#configurable-properties](https://docs.expo.dev/versions/latest/sdk/notifications/#configurable-properties)) you can then refer the sound in the `sound` field.
example: 
```
sound: 'bells_sound.wav',
```
If an invalid sound file (one that doesn't exist in the application bundle on the device) is specified in payload to Expo Push, default is played instead. Keep in mind sounds aren't played in silent mode or focus modes that may be set by user.

feat: support custom sounds

---

package.json
src/__tests__/ExpoClient-test.ts
yarn.lock

This decouples the tests from node-fetch, which makes it easier to replace.  (e: except with undici, I just confirmed that, https://github.com/mswjs/msw/issues/2165)
I [removed assertions against the sent requests](https://mswjs.io/docs/best-practices/avoid-request-assertions), and changed a few other tests: the test server, like the real server, will error if passed `useFcmV1=false`, so the test for that client option needs to expect that error.

Replace jest mocks with Mock Service Worker

---

.github/workflows/tests.yml

Since we require the checks before merging, this is necessary.  Since we can [approve workflow runs from contributors](https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/approving-workflow-runs-from-public-forks), it is also safe.

Run tests on Pull Requests

---

.github/workflows/release.yml

so far we released manually, but most of the changes are small and manual releases are annoying and delay new features. 
This integration should open a PR when there's stuff to release. When that PR is merged, a release happens automatically.

chore: add semi-automated publishing with release-please

---

.github/workflows/release.yml

To hopefully resolve a deadlock where https://github.com/expo/expo-server-sdk-node/pull/159 doesn't run required CI checks because the PR was opened by a GH action afaict. (https://github.com/googleapis/release-please/issues/922)
we could run the checks, but it's imo good enough to skip them

chore: skip ci on release

---

.github/workflows/release.yml
release-please-config.json

same as https://github.com/expo/expo-server-sdk-node/pull/160 but after reading the docs better

chore: skip ci on release pt2

---

.github/workflows/release.yml
release-please-config.json

reading  https://github.com/googleapis/release-please-action#basic-configuration
> Specifying a release-type configuration is the most straight-forward configuration option, but allows for no further customization.
_sigh_

chore: skip ci on release pt4

---

.github/workflows/tests.yml
package.json
tsconfig.json
yarn.lock

This has reached EOL.
I changed the target types and compilation output to node 20, and the CI tests to run on 20, 22, and 24.

chore!: Drop support for Node v18.x
